routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);

Route::get('admin/login','Backend\AdminController@login')->name('admin.login');
Route::prefix('admin')->middleware(['auth','web','admin'])->namespace('Backend')->group(function () {
    Route::get('/','AdminController@index');
    Route::get('download','DownloadController@index');
    Route::get('stats','AdminController@stats');
    Route::get('settings','SettingController@show')->name('settings.index');
    Route::post('settings/store','SettingController@store')->name('settings.store');
    Route::resource('users','UserController')->except('show');
    Route::resource('matches','MatchController')->except('show');
    Route::resource('pages','PageController')->except('show');
    Route::resource('orders','OrderController')->except('show');
    Route::get('order/remove/{order_id}/{sku}','OrderController@productRemove');
    Route::get('order/add/{order_id}/{sku}','OrderController@productAdd');
    Route::get('order/update/{order_id}/{sku}','OrderController@productUpdate');
    Route::resource('ordertemplates','OrderTemplateController')->except('show');
});

// Frontend Routes
Route::namespace('Frontend')->middleware(['web'])->group(function () {
    Route::get('/','IndexController@index')->name('home.index');
    Route::get('elemzes/{slug}','IndexController@match');
    Route::post('payments/paypal/create', 'PaymentController@createPaypal');
    Route::post('payments/paypal/backref/{orderID?}', 'PaymentController@getPaypal');
    Route::get('thankyou', 'PaymentController@thankyou');
    Route::get('cancel', 'PaymentController@cancel');

    Route::middleware(['auth'])->group(function () {
        Route::get('elofizetes', 'PaymentController@pay');
        Route::get('payments/paypal/create', 'PaymentController@createPaypal');
        Route::get('profile', 'ProfileController@index')->name('profile');
        Route::post('profile/update', 'ProfileController@update')->name('profile.update');
        Route::post('profile/password/change', 'ProfileController@changePassword')->name('profile.passwordchange');
        Route::delete('profile/delete', 'ProfileController@delete')->name('profile.delete');
    });

    Route::get('felhasznalasi-feltetelek', function () {
        return view('frontend.info.aszf.v10');
    });

    Route::get('adatkezelesi-tajekoztato', function () {
        return view('frontend.info.adatvedelem.v10');
    });

    Route::get('fizetesi-tajekoztato', function () {
        return view('frontend.info.fizetes.v10');
    });

    Route::get('gyik', function () {
        return view('frontend.info.gyik.gyik');
    });
    Route::get('kapcsolat', function () {
        return view('frontend.info.kapcsolat.kapcsolat');
    });
});

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Storage;
use App\Models\Order;
use Carbon\Carbon;

class AdminController extends Controller
{
    /**
     * Show admin home page
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function login()
    {
        return view('backend.login');
    }

    public function index()
    {
        $totalTraffic = Order::totalTraffic() ?? 0;
        $monthTraffic = Order::monthTraffic() ?? 0;
        $prevTraffic = Order::previousMonthTraffic() ?? 0;

        $totalOrders = Order::totalOrders() ?? 0;
        $monthOrders = Order::monthOrders() ?? 0;
        $prevOrders = Order::previousMonthOrders() ?? 0;
        $todayOrders = Order::todayOrders() ?? 0;

        return view('backend.index',
            compact('totalTraffic', 'monthTraffic', 'prevTraffic', 'totalOrders', 'monthOrders', 'prevOrders',
                'todayOrders'));
    }

    public function stats()
    {
        $months = [
            'Január',
            'Február',
            'Március',
            'Április',
            'Május',
            'Június',
            'Július',
            'Augusztus',
            'Szeptember',
            'Október',
            'November',
            'December'
        ];
        $results = [];
        $x = 1;
        while ($x <= 12) {
            $results[] = Order::whereStatus('completed')->whereRaw('MONTH(created_at) = '.$x)->count();
            $x++;
        }

        return response()->json(['months' => $months, 'results' =>$results]);
    }

    public function checkRemoteFile($url)
    {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_NOBODY, 1);
        curl_setopt($ch, CURLOPT_FAILONERROR, 1);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        if (curl_exec($ch) !== false) {
            return true;
        } else {
            return false;
        }
    }

    public function downloadImages()
    {
        $products = \App\Models\Product::select('image')->whereNotNull('image')->groupBy('image')->get();
        foreach ($products as $product) {
            $image = ltrim($product->image, '/');
            $url = 'https://www.motoralkatresznagyker.com/media/catalog/product/' . $image;
            if ($this->checkRemoteFile($url)) {
                $contents = file_get_contents($url);
                Storage::disk('local')->put('public/images/' . $image, $contents);
            }
        }
    }
}

app/Http/Controllers/Backend/DownloadController.php
<?php

namespace App\Http\Controllers\Backend;
use Storage;
use App\Http\Controllers\Controller;
use App\Models\Match;
use Auth;

class DownloadController extends Controller
{
    public function downloadImage($url)
    {
        $path = explode('.', basename($url));
        $path = str_slug($path[0]) . '.' . $path[1];
        $client = new \GuzzleHttp\Client();
        try {
            $resource = fopen(storage_path('app/public/logo/' . $path), 'w+');
            @$client->request('GET', $url, [
                'sink' => $resource
            ]);

            return basename(storage_path('app/public/logo/' . $path));
        } catch (\Exception $e) {
            return false;
        }
        return false;
    }

    public function setMatches()
    {
        $data = Storage::disk('local')->get('matches.json');
        $data = json_decode($data);
        $i=0;
        $matches = [];
        foreach ($data as $key => $match) {
            if ($match->status != 'publish' || Match::where('api_id', $match->id)->count() == 1) {
                continue;
            }
            
            if(!isset($match->the_meta->api_preview_json)){
                continue;
            }
            $api = json_decode($match->the_meta->api_preview_json[0]);
            if(empty($api->hometeam)){
                continue;
            }
            if($api == null){
                continue;
            }

            $matches[$key]['id'] = $match->id;
            $matches[$key]['slug'] = $match->slug;
            $matches[$key]['team'] = $api->hometeam;
            $matches[$key]['teamlogo'] = 'https://www.freesupertips.co.uk/wp-content/themes/freesupertips/image/team/' . $api->hometeam . '.png';
            $matches[$key]['team2'] = $api->awayteam;
            $matches[$key]['team2logo'] = 'https://www.freesupertips.co.uk/wp-content/themes/freesupertips/image/team/' . $api->awayteam . '.png';
            $matches[$key]['league'] = $match->the_meta->_league[0] ?? null;
            $matches[$key]['stadion'] = $match->the_meta->_stadium[0] ?? null;
            $matches[$key]['stats'][] = $match->the_meta->_headtohead[0] ?? null;
            $matches[$key]['stats'][] = $match->the_meta->_stats[0] ?? null;
            $matches[$key]['tips'][] = $match->the_meta->api_outcome_1[0] ?? null;
            $matches[$key]['tips'][] = $match->the_meta->api_outcome_2[0] ?? null;
            $matches[$key]['dateslug'] = $match->the_meta->_start_year[0] . "-" . $match->the_meta->_start_month[0] . "-" . $match->the_meta->_start_day[0];
            $matches[$key]['date'] = \Carbon\Carbon::parse($match->the_meta->_start_year[0] . "-" . $match->the_meta->_start_month[0] . "-" . $match->the_meta->_start_day[0] . " " . $match->the_meta->_kickoff[0] . ":00")
                ->addHour(1);
        }

        foreach ($matches as $matchdata)
        {
            $check = Match::where('api_id',$matchdata['id']);

            if($check->count()>0){
                continue;
            }

            $team_logo = $this->downloadImage($matchdata['teamlogo']);
            $team2_logo = $this->downloadImage($matchdata['team2logo']);

            $match = new Match();
            $match->api_id = $matchdata['id'];
            $match->user_id = Auth::user()->id;
            $match->team = $matchdata['team'];
            $match->team_logo = $team_logo;
            $match->team2 = $matchdata['team2'];
            $match->team2_logo = $team2_logo;
            $match->title = $match->team.' vs '.$match->team2.' '.$matchdata['dateslug'];
            $match->slug = str_slug($match->title);
            $match->reason = implode("<br/>", $matchdata['stats']);
            $match->tips = implode("<br/>", $matchdata['tips']);
            $match->started_at = $matchdata['date'];
            $match->stadium = $matchdata['stadion'] ?? null;
            $match->league = $matchdata['league'] ?? null;
            $match->free = 0;
            $match->status = 0;
            $match->save();
        }

    }

    public function index()
    {
        $this->download();
        $this->setMatches();

        return redirect('admin/matches');
    }

    public function download()
    {
        $url = 'https://www.freesupertips.co.uk/wp-json/wp/v2/previews/';
        $client = new \GuzzleHttp\Client();
        $res = $client->request('GET', $url);

        Storage::disk('local')->put('matches.json', $res->getBody());
    }
}

app/Http/Controllers/Backend/MatchController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Match;
use App\Http\Requests\Backend\MatchCreateRequest;
use App\Http\Requests\Backend\MatchUpdateRequest;
use Carbon\Carbon;
use Illuminate\Http\Request;

class MatchController extends Controller
{
    /**
     * Show matches
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Match $match)
    {
        $data = $match->get();

        return view('backend.matches.index', compact('data'));
    }

    /**
     * Create Match
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(Match $match)
    {
        return view('backend.matches.form', compact('match'));
    }

    /**
     * Store Match
     *
     * @param \App\Http\Requests\Backend\MatchCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $match = new Match;
        $match->team = $request->team;

        if ($request->has('team_logo')) {
            $path = $request->file('team_logo')->store('public/logo');
            $match->team_logo = basename($path);
        }

        if ($request->has('team2_logo')) {
            $path = $request->file('team2_logo')->store('public/logo');
            $match->team2_logo = basename($path);
        }

        $match->team2 = $request->team2;
        $match->stadium = $request->stadium;
        $match->league = $request->league;
        $match->free = $request->free ?? 0;
        $match->status = $request->status ?? 0;
        $match->save();

        return redirect(route('matches.index'));
    }

    /**
     * Edit Match
     *
     * @param \App\Models\Match $match
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Match $match)
    {
        return view('backend.matches.form', compact('match'));
    }

    /**
     * Update Match
     *
     * @param \App\Http\Requests\Backend\MatchUpdateRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request)
    {
        //@todo: validalas
        $match = Match::find($request->id);
        $match->team = $request->team;
        $match->team2 = $request->team2;
        if ($request->has('team_logo')) {
            $path = $request->file('team_logo')->store('public/logo');
            $match->team_logo = basename($path);
        }

        if ($request->has('team2_logo')) {
            $path = $request->file('team2_logo')->store('public/logo');
            $match->team2_logo = basename($path);
        }
        $match->stadium = $request->stadium;
        $match->league = $request->league;
        $match->free = $request->free ?? 0;
        $match->status = $request->status ?? 0;
        $match->reason = $request->reason;
        $match->tips = $request->tips;
        $match->update();

        return redirect(route('matches.edit',$request->id));
    }

    /**
     * Destroy Match
     *
     * @param \App\Models\Match $match
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Match $match)
    {
        $match->delete();
        return back();
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\OrderProducts;
use App\Models\OrderTemplates;
use App\Http\Requests\Backend\OrderCreateRequest;
use App\Http\Requests\Backend\OrderUpdateRequest;
use Illuminate\Http\Request;
use App\Notifications\OrderEmail;
use App\Models\OrderLogs;

class OrderController extends Controller
{
    /**
     * Show pages
     *
     * @param \App\Models\Order $order
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Order $order)
    {
        $data = $order->get();
        return view('backend.orders.index', compact('data'));
    }
    /**
     * Edit page
     *
     * @param \App\Models\Order $order
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Order $order)
    {
        $order = Order::find($order->id);
        return view('backend.orders.form', compact('order'));
    }

    /**
     * Update page
     *
     * @param \App\Http\Requests\Backend\PageUpdateRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(OrderUpdateRequest $request)
    {
        $order = Order::find($request->id);
        $template_id = $order->template_id;
        $order->firstname = $request->firstname;
        $order->lastname = $request->lastname;
        $order->email = $request->email;
        $order->phone = $request->phone;
        $order->company = $request->company;
        $order->taxnumber = $request->taxnumber;
        $order->country = $request->country;
        $order->city = $request->city;
        $order->zip = $request->zip;
        $order->street = $request->street;
        $order->delivery_firstname = $request->delivery_firstname;
        $order->delivery_lastname = $request->delivery_lastname;
        $order->delivery_phone = $request->delivery_phone;
        $order->delivery_taxnumber = $request->delivery_taxnumber;
        $order->delivery_country = $request->delivery_country;
        $order->delivery_city = $request->delivery_city;
        $order->delivery_zip = $request->delivery_zip;
        $order->delivery_street = $request->delivery_street;
        $order->delivery_company = $request->delivery_company;
        $order->template_id = $request->template_id;
        $order->update();

        if(isset($request->sendemail)){
            $order->notify(new OrderEmail($order->template_id,$order));
        }

        if($template_id != $order->template_id) {
            OrderLogs::create([
                'order_id'=>$request->id,
                'message'=>"A rendelés állapota: ".$order->status->title
            ]);
        }

        return redirect(route('orders.edit',$request->id));
    }

    /**
     * Destroy page
     *
     * @param \App\Models\Order $order
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Order $order)
    {
        $order->delete();
        return back();
    }
}

app/Http/Controllers/Backend/SettingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Setting;
use App\Http\Requests\Frontend\SettingUpdateRequest;

class SettingController extends Controller
{
    /**
     * Show users
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Setting $setting)
    {
        $settings = $setting->get();
        return view('backend.settings.form', compact('settings'));
    }

    public function store(SettingUpdateRequest $request)
    {
        Setting::updateOrCreate(['key' => 'price'], ['value' => $request->price]);
        Setting::updateOrCreate(['key' => 'saleprice'], ['value' => $request->saleprice]);


        return redirect(route('settings.index'));
    }

}

resources/views/backend/pages/form.blade.php
@extends('backend.backend')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content mt-3">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    @if(isset($page->id))
                                        Oldal szerkesztése
                                    @else
                                        Új olddal
                                    @endif
                                </h3>

                                <div class="card-tools">

                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-2">
                                @if(isset($page->id))
                                    {!! Form::model($page, ['method' => 'put', 'route' => ['pages.update', $page->id]])  !!}
                                    <input type="hidden" name="id" value="{{$page->id}}">
                                @else
                                    {!! Form::model($page, ['method' => 'store', 'route' => ['pages.store']])  !!}
                                @endif

                                <div class="form-group has-feedback @if ($errors->has('title')) has-error @endif">
                                    {{ Form::label('title', 'Cím') }}
                                    {!! Form::text('title', null, ['class' => 'form-control col-md-4', 'id' => 'title']) !!}
                                    @if ($errors->has('title'))
                                        <span class="help-block" role="alert">
                                                {{ $errors->first('title') }}
                                            </span>
                                    @endif
                                </div>

                                <div class="form-group has-feedback @if ($errors->has('slug')) has-error @endif">
                                    {{ Form::label('slug', 'Url') }}
                                    {!! Form::text('slug', null, ['class' => 'form-control col-md-4', 'id' => 'slug']) !!}
                                    @if ($errors->has('slug'))
                                        <span class="help-block" role="alert">
                                            {{ $errors->first('slug') }}
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group has-feedback @if ($errors->has('meta_title')) has-error @endif">
                                    {{ Form::label('meta_title', 'Meta Cím') }}
                                    {!! Form::text('meta_title', null, ['class' => 'form-control col-md-4', 'id' => 'meta_title']) !!}
                                    @if ($errors->has('meta_title'))
                                        <span class="help-block" role="alert">
                                        {{ $errors->first('meta_title') }}
                                    </span>
                                    @endif
                                </div>
                                <div
                                    class="form-group has-feedback @if ($errors->has('meta_description')) has-error @endif">
                                    {{ Form::label('meta_description', 'Meta leírás') }}
                                    {!! Form::text('meta_description', null, ['class' => 'form-control col-md-4', 'id' => 'meta_description']) !!}
                                    @if ($errors->has('meta_description'))
                                        <span class="help-block" role="alert">
                                    {{ $errors->first('meta_description') }}
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group has-feedback @if ($errors->has('description')) has-error @endif">
                                    {{ Form::label('description', 'Tartalom') }}
                                    {!! Form::textarea('description', null, ['class' => 'summernote form-control col-md-4', 'id' => 'description']) !!}
                                    @if ($errors->has('description'))
                                        <span class="help-block" role="alert">
                                {{ $errors->first('description') }}
                                </span>
                                    @endif
                                </div>
                                <div class="form-group has-feedback @if ($errors->has('widget')) has-error @endif">
                                    {{ Form::label('widget', 'Widget') }}
                                    {!! Form::select('widget',$widgets,null,['class' => 'form-control col-md-4', 'id' => 'widget']) !!}
                                    @if ($errors->has('widget'))
                                        <span class="help-block" role="alert">
                                    {{ $errors->first('widget') }}
                                </span>
                                    @endif
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Mentés</button>
                            </div>

                            {!! Form::close()  !!}
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
    <!-- /.content-wrapper -->
@endsection

resources/views/backend/pages/index.blade.php
@extends('backend.backend')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content mt-3">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Oldalak</h3>

                                <div class="card-tools">
                                    <a href="{{ route('pages.create') }}" class="btn btn-info btn-sm"><i class="fa fa-plus"></i> Új oldal</a>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-1">
                                <table id="pages" class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Cím</th>
                                        <th>Link</th>
                                        <th>Seo cím</th>
                                        <th>Seo leírás</th>
                                        <th>#</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($data as $row)
                                        <tr>
                                            <td>{{$row->id}}</td>
                                            <td>{{$row->title}}</td>
                                            <td>{{$row->slug}}</td>
                                            <td>{{$row->meta_title}}</td>
                                            <td>{{$row->meta_description}}</td>
                                            <td class="text-center">
                                                <div class="row pull-right">
                                                    <div class="d-inline mr-1">
                                                        <a href="{{route('pages.edit',['id'=>$row->id])}}"
                                                           class="btn btn-sm btn-info"><i class="fa fa-pencil"></i></a>
                                                    </div>
                                                    <div class="d-inline">
                                                        <form action="{{ route('pages.destroy',['id'=>$row->id]) }}"
                                                              method="POST">
                                                            <input type="hidden" name="_method" value="DELETE">
                                                            <input type="hidden" name="_token"
                                                                   value="{{ csrf_token() }}">
                                                            <button type="submit"
                                                                    class="d-inline btn btn-sm btn-danger"><i
                                                                        class="fa fa-times"></i></button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection